// Every Pokémon TCG set, 1999–2026, grouped by era (newest first).
// Factual reference data only (set names + release years) — used to power the
// /pokemon-sets browse page and, optionally, the "Set" field on /admin.
export const POKEMON_ERAS = [
  {
    era: "Mega Evolution",
    years: "2025–2026",
    sets: [
      "Pitch Black",
      "Chaos Rising",
      "Perfect Order",
      "Ascended Heroes",
      "Phantasmal Flames",
      "Mega Evolution",
    ],
  },
  {
    era: "Scarlet & Violet",
    years: "2023–2025",
    sets: [
      "White Flare",
      "Black Bolt",
      "Destined Rivals",
      "Journey Together",
      "Prismatic Evolutions",
      "Surging Sparks",
      "Stellar Crown",
      "Shrouded Fable",
      "Twilight Masquerade",
      "Temporal Forces",
      "Paldean Fates",
      "Paradox Rift",
      "151",
      "Obsidian Flames",
      "Paldea Evolved",
      "Scarlet & Violet",
    ],
  },
  {
    era: "Sword & Shield",
    years: "2020–2023",
    sets: [
      "Crown Zenith",
      "Silver Tempest",
      "Lost Origin",
      "Pokémon GO",
      "Astral Radiance",
      "Brilliant Stars",
      "Fusion Strike",
      "Celebrations",
      "Evolving Skies",
      "Chilling Reign",
      "Battle Styles",
      "Shining Fates",
      "Vivid Voltage",
      "Champion's Path",
      "Darkness Ablaze",
      "Rebel Clash",
      "Sword & Shield",
    ],
  },
  {
    era: "Sun & Moon",
    years: "2017–2019",
    sets: [
      "Cosmic Eclipse",
      "Hidden Fates",
      "Unified Minds",
      "Unbroken Bonds",
      "Detective Pikachu",
      "Team Up",
      "Lost Thunder",
      "Dragon Majesty",
      "Celestial Storm",
      "Forbidden Light",
      "Ultra Prism",
      "Crimson Invasion",
      "Shining Legends",
      "Burning Shadows",
      "Guardians Rising",
      "Sun & Moon",
    ],
  },
  {
    era: "XY",
    years: "2013–2016",
    sets: [
      "Evolutions",
      "Steam Siege",
      "Fates Collide",
      "Generations",
      "BREAKpoint",
      "BREAKthrough",
      "Ancient Origins",
      "Roaring Skies",
      "Double Crisis",
      "Primal Clash",
      "Phantom Forces",
      "Furious Fists",
      "Flashfire",
      "XY",
      "Kalos Starter Set",
    ],
  },
  {
    era: "Black & White",
    years: "2011–2013",
    sets: [
      "Legendary Treasures",
      "Plasma Blast",
      "Plasma Freeze",
      "Plasma Storm",
      "Boundaries Crossed",
      "Dragon Vault",
      "Dragons Exalted",
      "Dark Explorers",
      "Next Destinies",
      "Noble Victories",
      "Emerging Powers",
      "Black & White",
    ],
  },
  { era: "Call of Legends", years: "2011", sets: ["Call of Legends"] },
  {
    era: "HeartGold & SoulSilver",
    years: "2010",
    sets: ["Triumphant", "Undaunted", "Unleashed", "HeartGold SoulSilver"],
  },
  {
    era: "Platinum",
    years: "2009",
    sets: ["Pokémon Rumble", "Arceus", "Supreme Victors", "Rising Rivals", "Platinum"],
  },
  {
    era: "Diamond & Pearl",
    years: "2007–2008",
    sets: [
      "Stormfront",
      "Legends Awakened",
      "Majestic Dawn",
      "Great Encounters",
      "Secret Wonders",
      "Mysterious Treasures",
      "Diamond & Pearl",
    ],
  },
  {
    era: "EX",
    years: "2003–2007",
    sets: [
      "Power Keepers",
      "Dragon Frontiers",
      "Crystal Guardians",
      "Holon Phantoms",
      "Legend Maker",
      "Delta Species",
      "Unseen Forces",
      "Emerald",
      "Deoxys",
      "Team Rocket Returns",
      "FireRed & LeafGreen",
      "Hidden Legends",
      "Team Magma vs Team Aqua",
      "Dragon",
      "Sandstorm",
      "Ruby & Sapphire",
    ],
  },
  {
    era: "E-Card",
    years: "2002–2003",
    sets: ["Skyridge", "Aquapolis", "Expedition Base Set"],
  },
  { era: "Legendary Collection", years: "2002", sets: ["Legendary Collection"] },
  {
    era: "Neo",
    years: "2000–2002",
    sets: ["Neo Destiny", "Neo Revelation", "Southern Islands", "Neo Discovery", "Neo Genesis"],
  },
  { era: "Gym", years: "2000", sets: ["Gym Challenge", "Gym Heroes"] },
  {
    era: "Base",
    years: "1999–2000",
    sets: ["Team Rocket", "Base Set 2", "Fossil", "Jungle", "Base Set"],
  },
];

export const ALL_POKEMON_SETS = POKEMON_ERAS.flatMap((e) => e.sets);
